### ISSUE TITLE
Download the subtitle from videos

### ISSUE THREAD

**Issue by AnakTeka** [cristian-gabbanini/fem-downloader#5]
Thank you for this library, is there anyway to download caption from the videos?

**Comment by cristian-gabbanini** [comment]
Hi!
Good question!
I'll have a look at how subtitles are managed but I would assume that would be possible.
If you think this feature could be useful I'd give it a shot and try a first implementation as soon as I can.

Thanks!
Crsistian 

P.S. Would you mind starring the repo so that the other users could find it more easily?

**Comment by cristian-gabbanini** [comment]
Hey,
let me know if you think this could be useful....got a pull request almost ready to be merged
